<?php

namespace Oreha\ErpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisRepository extends EntityRepository
{
    
    public function findNbDossiersAvecDevisPerdusParSource($id){
        $q = $this->createQueryBuilder('de');
        
        $q
                ->select('COUNT(de) as nombreDevisPerdus')
                ->innerJoin('Oreha\ErpBundle\Entity\Dossier', 'do', 'WITH', 'de.dossier = do')
                ->innerJoin('Oreha\ErpBundle\Entity\Statut', 'st', 'WITH', 'st.dossier = do')
                ->innerJoin('Oreha\ErpBundle\Entity\Source', 'so', 'WITH', 'do.source = so')
                ->where('so.id = :id')
                ->andWhere('st.libelle = \'perdu\' ')
                ->groupBy('so')
                ->setParameter(':id', $id)
        ;
        $arr = $q->getQuery()->execute();
        return @$arr[0]['nombreDevisPerdus'];
    }
    
    
    public function findNbDossiersAvecDevisPerdusParSource2($id){
        $q = $this->createQueryBuilder('de');
        
        $q
                ->select('COUNT(de) as nombreDevisPerdus')
                ->innerJoin('Oreha\ErpBundle\Entity\Dossier', 'do', 'WITH', 'de.dossier = do')
                ->innerJoin('Oreha\ErpBundle\Entity\Statut', 'st', 'WITH', 'st.dossier = do')
                ->innerJoin('Oreha\ErpBundle\Entity\Source', 'so', 'WITH', 'do.source = so')
                ->where('so.id = :id')
                ->andWhere('st.libelle = \'perdu\' ')
                ->groupBy('so')
                ->setParameter(':id', $id)
        ;
        $arr = $q->getQuery()->execute();
        return @$arr[0]['nombreDevisPerdus'];
    }
    
}
