<?php

namespace Oreha\ErpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EcheanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcheanceRepository extends EntityRepository
{
   /**
    * Retourne la liste des echeances qu'un utilisateur doit traiter
    * @param integer $user
    * @return ArrayCollection
    */ 
    public function findEcheancesATrairerUser($user){
        $qb = $this->createQueryBuilder('e');
        
        $qb
                ->select('e')
                ->where('e.user = :user AND e.avancement < 100 AND e.date < :now')
                ->orderBy('e.date', 'ASC')
                ->setParameter('user', $user)
                ->setParameter('now', new \DateTime('now'))
        ;
        
        return $qb->getQuery()->execute();
    }
    
    
}
