<?php

namespace Oreha\ErpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamillePrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamillePrestationRepository extends EntityRepository
{
}
