<?php

namespace Oreha\ErpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PretRepository extends EntityRepository
{
    
    /**
     * Recupère le total des prets sur un dossier
     * @param type $id
     */
    public function getTotal($idDossier){
        $qb = $this->createQueryBuilder('p');
        $qb
                ->select('SUM(p)')
                ->where('p.dossier = :dossier')
                ->setParameter('dossier', $idDossier)
        ;
        
        return $qb->getQuery()->execute();
    }
}
