<?php
namespace Oreha\ErpBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * StatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutRepository extends EntityRepository
{
    /**
     * 
     * @param integer $id id du dossier
     * @return float
     */
    public function getLastBudget($id){
        ## TODO IMPLEMENT ME
    }
    
   
    public function findTransfertsEnAttenteValidation(){
        $qb = $this->createQueryBuilder('s');
        $qb
                ->select('s')
                ->where('s.libelle = :gagne')
                ->setParameter('gagne', 'gagne')
        ;
        
        return $qb->getQuery()->execute();
    }


    /**
     * FOR TESTING PURPOSES
     * Retourne le nombre à affecter pour le code du nouveau statut
     */
    public function makeNum($idDossier, $chr){
        $qb = $this->createQueryBuilder('s');
        $qb
                ->select('COUNT(s)')
                ->where('s.dossier = :dossier AND s.chr = :chr')
                ->setParameter('dossier', $idDossier)
                ->setParameter('chr', $chr)
        ;
        $num = $qb->getQuery()->execute();
        $num = $num[0][1];
        
        return $num;
    }
}
