<?php

namespace Oreha\ErpBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminController__JMSInjector
{
    public static function inject($container) {
        require_once 'F:/wamp/www/oreha/app/cache/dev/jms_diextra/proxies/Oreha-ErpBundle-Controller-AdminController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Oreha\\ErpBundle\\Controller\\AdminController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'reloadDossiersAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxya3db2306_58059d927ca75e9c01053fc74815eae2087da3f4\__CG__\Oreha\ErpBundle\Controller\AdminController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
