<?php

namespace Oreha\ErpBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DossierController__JMSInjector
{
    public static function inject($container) {
        require_once 'F:/wamp/www/oreha/app/cache/dev/jms_diextra/proxies/Oreha-ErpBundle-Controller-DossierController.php';
        $b = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Oreha\\ErpBundle\\Controller\\DossierController' => array('validerClientAction' => array(0 => 'security.access.method_interceptor'), 'refuserClientAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxya3db2306_e421925d3620e66c183862cd6d18e7114e00f92b\__CG__\Oreha\ErpBundle\Controller\DossierController();
        $instance->__CGInterception__setLoader($b);
        return $instance;
    }
}
