<?php

namespace Oreha\ErpBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DemoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Oreha\ErpBundle\Controller\DemoController();
        return $instance;
    }
}
