<?php

namespace Oreha\ErpBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StatsController__JMSInjector
{
    public static function inject($container) {
        require_once 'F:/wamp/www/oreha/app/cache/dev/jms_diextra/proxies/Oreha-ErpBundle-Controller-StatsController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Oreha\\ErpBundle\\Controller\\StatsController' => array('managerIndexAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxya3db2306_eed3d8aa85c7d574eafce4c75d5987cbd58ae3e8\__CG__\Oreha\ErpBundle\Controller\StatsController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
