<?php

namespace Oreha\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UserController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Oreha\UserBundle\Controller\UserController();
        return $instance;
    }
}
