<?php

namespace Oreha\ErpBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FamilleCEEController__JMSInjector
{
    public static function inject($container) {
        require_once 'F:/wamp/www/oreha/app/cache/dev/jms_diextra/proxies/Oreha-ErpBundle-Controller-FamilleCEEController.php';
        $c = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Oreha\\ErpBundle\\Controller\\FamilleCEEController' => array('listeAction' => array(0 => 'security.access.method_interceptor'), 'ajouterFamilleAction' => array(0 => 'security.access.method_interceptor'), 'voirFamilleAction' => array(0 => 'security.access.method_interceptor'), 'modifierFamilleAction' => array(0 => 'security.access.method_interceptor'), 'supprimerFamilleAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxya3db2306_44c135d520586041e5192d17523fd81914b93fb6\__CG__\Oreha\ErpBundle\Controller\FamilleCEEController();
        $instance->__CGInterception__setLoader($c);
        return $instance;
    }
}
