<?php

namespace Proxies\__CG__\Oreha\ErpBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dossier extends \Oreha\ErpBundle\Entity\Dossier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'intitule', 'typeDossier', 'dateCloture', 'raisonCloture', 'description', 'supprime', 'appreciation', 'contacts', 'biens', 'commentaires', 'statuts', 'echeances', 'rendezvouss', 'source', 'prets', 'deviss', 'users', 'prestations', 'declarations', 'client_id', 'factures', 'payements');
        }

        return array('__isInitialized__', 'id', 'intitule', 'typeDossier', 'dateCloture', 'raisonCloture', 'description', 'supprime', 'appreciation', 'contacts', 'biens', 'commentaires', 'statuts', 'echeances', 'rendezvouss', 'source', 'prets', 'deviss', 'users', 'prestations', 'declarations', 'client_id', 'factures', 'payements');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dossier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getChrono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChrono', array());

        return parent::getChrono();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', array());

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function clearUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearUsers', array());

        return parent::clearUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function reloadUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'reloadUsers', array());

        return parent::reloadUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersid', array());

        return parent::getUsersid();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantTotalPrets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantTotalPrets', array());

        return parent::getMontantTotalPrets();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantTotalPrestations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantTotalPrestations', array());

        return parent::getMontantTotalPrestations();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantTotalMarcheHT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantTotalMarcheHT', array());

        return parent::getMontantTotalMarcheHT();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantMarcheTTC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantMarcheTTC', array());

        return parent::getMontantMarcheTTC();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantMarcheTVAReduite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantMarcheTVAReduite', array());

        return parent::getMontantMarcheTVAReduite();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantMarcheTVANormale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantMarcheTVANormale', array());

        return parent::getMontantMarcheTVANormale();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalFacture', array());

        return parent::getTotalFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPaye', array());

        return parent::getTotalPaye();
    }

    /**
     * {@inheritDoc}
     */
    public function getBalanceFacturation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalanceFacturation', array());

        return parent::getBalanceFacturation();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntitule($intitule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntitule', array($intitule));

        return parent::setIntitule($intitule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntitule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntitule', array());

        return parent::getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDossier($typeDossier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDossier', array($typeDossier));

        return parent::setTypeDossier($typeDossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDossier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDossier', array());

        return parent::getTypeDossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCloture($dateCloture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCloture', array($dateCloture));

        return parent::setDateCloture($dateCloture);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCloture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCloture', array());

        return parent::getDateCloture();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonCloture($raisonCloture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonCloture', array($raisonCloture));

        return parent::setRaisonCloture($raisonCloture);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonCloture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonCloture', array());

        return parent::getRaisonCloture();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupprime($supprime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupprime', array($supprime));

        return parent::setSupprime($supprime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupprime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupprime', array());

        return parent::getSupprime();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppreciation($appreciation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppreciation', array($appreciation));

        return parent::setAppreciation($appreciation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppreciation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppreciation', array());

        return parent::getAppreciation();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientId($clientId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientId', array($clientId));

        return parent::setClientId($clientId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientId', array());

        return parent::getClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\Oreha\ErpBundle\Entity\Contact $contacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', array($contacts));

        return parent::addContact($contacts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\Oreha\ErpBundle\Entity\Contact $contacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', array($contacts));

        return parent::removeContact($contacts);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', array());

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addBien(\Oreha\ErpBundle\Entity\Bien $biens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBien', array($biens));

        return parent::addBien($biens);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBien(\Oreha\ErpBundle\Entity\Bien $biens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBien', array($biens));

        return parent::removeBien($biens);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiens', array());

        return parent::getBiens();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\Oreha\ErpBundle\Entity\Commentaire $commentaires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', array($commentaires));

        return parent::addCommentaire($commentaires);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\Oreha\ErpBundle\Entity\Commentaire $commentaires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', array($commentaires));

        return parent::removeCommentaire($commentaires);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', array());

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function addStatut(\Oreha\ErpBundle\Entity\Statut $statuts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStatut', array($statuts));

        return parent::addStatut($statuts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStatut(\Oreha\ErpBundle\Entity\Statut $statuts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStatut', array($statuts));

        return parent::removeStatut($statuts);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatuts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatuts', array());

        return parent::getStatuts();
    }

    /**
     * {@inheritDoc}
     */
    public function addEcheance(\Oreha\ErpBundle\Entity\Echeance $echeances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEcheance', array($echeances));

        return parent::addEcheance($echeances);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEcheance(\Oreha\ErpBundle\Entity\Echeance $echeances)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEcheance', array($echeances));

        return parent::removeEcheance($echeances);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcheances()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcheances', array());

        return parent::getEcheances();
    }

    /**
     * {@inheritDoc}
     */
    public function addRendezvouss(\Oreha\ErpBundle\Entity\Rendezvous $rendezvouss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRendezvouss', array($rendezvouss));

        return parent::addRendezvouss($rendezvouss);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRendezvouss(\Oreha\ErpBundle\Entity\Rendezvous $rendezvouss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRendezvouss', array($rendezvouss));

        return parent::removeRendezvouss($rendezvouss);
    }

    /**
     * {@inheritDoc}
     */
    public function getRendezvouss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRendezvouss', array());

        return parent::getRendezvouss();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource(\Oreha\ErpBundle\Entity\Source $source = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', array($source));

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', array());

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function addPret(\Oreha\ErpBundle\Entity\Pret $prets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPret', array($prets));

        return parent::addPret($prets);
    }

    /**
     * {@inheritDoc}
     */
    public function removePret(\Oreha\ErpBundle\Entity\Pret $prets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePret', array($prets));

        return parent::removePret($prets);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrets', array());

        return parent::getPrets();
    }

    /**
     * {@inheritDoc}
     */
    public function addDeviss(\Oreha\ErpBundle\Entity\Devis $deviss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDeviss', array($deviss));

        return parent::addDeviss($deviss);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDeviss(\Oreha\ErpBundle\Entity\Devis $deviss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDeviss', array($deviss));

        return parent::removeDeviss($deviss);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviss', array());

        return parent::getDeviss();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\Oreha\UserBundle\Entity\User $users)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', array($users));

        return parent::addUser($users);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\Oreha\UserBundle\Entity\User $users)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', array($users));

        return parent::removeUser($users);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', array());

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrestation(\Oreha\ErpBundle\Entity\Prestation $prestations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrestation', array($prestations));

        return parent::addPrestation($prestations);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrestation(\Oreha\ErpBundle\Entity\Prestation $prestations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrestation', array($prestations));

        return parent::removePrestation($prestations);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrestations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrestations', array());

        return parent::getPrestations();
    }

    /**
     * {@inheritDoc}
     */
    public function addDeclaration(\Oreha\ErpBundle\Entity\DeclarationAdministrative $declarations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDeclaration', array($declarations));

        return parent::addDeclaration($declarations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDeclaration(\Oreha\ErpBundle\Entity\DeclarationAdministrative $declarations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDeclaration', array($declarations));

        return parent::removeDeclaration($declarations);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclarations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeclarations', array());

        return parent::getDeclarations();
    }

    /**
     * {@inheritDoc}
     */
    public function addFacture(\Oreha\ErpBundle\Entity\Facture $factures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFacture', array($factures));

        return parent::addFacture($factures);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFacture(\Oreha\ErpBundle\Entity\Facture $factures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFacture', array($factures));

        return parent::removeFacture($factures);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactures', array());

        return parent::getFactures();
    }

    /**
     * {@inheritDoc}
     */
    public function addPayement(\Oreha\ErpBundle\Entity\Payement $payements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPayement', array($payements));

        return parent::addPayement($payements);
    }

    /**
     * {@inheritDoc}
     */
    public function removePayement(\Oreha\ErpBundle\Entity\Payement $payements)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePayement', array($payements));

        return parent::removePayement($payements);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayements', array());

        return parent::getPayements();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDerniereModif($dateDerniereModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDerniereModif', array($dateDerniereModif));

        return parent::setDateDerniereModif($dateDerniereModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDerniereModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDerniereModif', array());

        return parent::getDateDerniereModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateur(\Oreha\UserBundle\Entity\User $createur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateur', array($createur));

        return parent::setCreateur($createur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateur', array());

        return parent::getCreateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setDernierModificateur(\Oreha\UserBundle\Entity\User $dernierModificateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDernierModificateur', array($dernierModificateur));

        return parent::setDernierModificateur($dernierModificateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDernierModificateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDernierModificateur', array());

        return parent::getDernierModificateur();
    }

}
